let config = {
  elo: 3500,
  coach: 999,
  lines: 5,
  colors: ["#0000ff", "#00ff00", "#FFFF00", "#f97316", "#ff0000"],
  depth: 10,
  depth2: 10,
  delay: 100,
  style: "Default",
  autoMove: false,
  floatingBtn: false,
  speach: false,
  moveClassification: false,
  autoStart: false,
  winningMove: false,
  showEval: false,
  onlyShowEval: false,
  key: "a",
  key2: "z",
};